apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: poulomi-app-1
  namespace: default
spec:
  interval: 1m
  path: "./flux-cd/reporsitories/poulomi-app1/deploy"
  prune: true
  sourceRef:
    kind: GitRepository
    name: poulomi-app-1
